### ISSUE TITLE
Public link is not accessible

### ISSUE THREAD

**Issue by nikahmadz** [WebCrateApp/webcrate#47]
### 🏷️ WebCrate Version

v1.4.0

### ⚙️ Environment

Chrome, Other (please specify below)

### 🐞 Describe the bug

I use WebCrate on Chrome and Brave.
Trying to share what is supposed to be a public link (https://webcrate.nikahmad.deta.app/link/public/j6oIXfg4tJqjOXTG)

### 📚 To Reproduce

Create a link in a Crate and then enable sharing.
Open other browser or a new private tab, then open the shared link.

### 💡 Expected behavior

That link can be open on any browser.

### 📋 Additional context

It should work like sharing this crate: https://webcrate.nikahmad.deta.app/crate/public/vs8m95QyZesqRZjW

**Comment by nikahmadz** [comment]
> Your link works fine for me.
> 
> Are you getting any errors?

Open the link using **new private tab** (which represent public access to the link)
I got 'Unauthorized' reply on the browser screen. 

You may get it because you're logged in to the app.

**Comment by BetaHuhn** [comment]
> Open the link using new private tab (which represent public access to the link)

I tried it using a private tab (in Brave and Firefox) and it works in both.

> You may get it because you're logged in to the app.

If I was logged in I should still get `Unauthorized` if the link wasn't actually set to public since I shouldn't be able to access your WebCrate instance.

> I got 'Unauthorized' reply on the browser screen.

Weird, I don't know why it doesn't work for you. I will raise this with the [Deta](https://deta.sh) Team (the service WebCrate runs on) since I don't have any control over the authentication stuff myself. Will get back to you as soon as I know something new.

**Comment by xeust** [comment]
Hi @nikahmadz, this is Max from Deta.

Could you please try again? 

We had a stale state in our Asia Edge-gateway that should be up to date now, sorry about this!

**Comment by nikahmadz** [comment]
When I open the app, I got an update notification:
```
WebCrate
v1.4.1
Add Web Share Target API; Add enter shortcut to name screen on welcome page; Bug fixes
```
Then test the app, ***now it works!*** thanks.

I guess Asian gateway was outdated. now its working.
